### ISSUE TITLE
expo-video-player not working for expo version 36

### ISSUE THREAD

**Issue by devramjava** [ihmpavel/expo-video-player#65] opened 2020-02-12 09:32 UTC
App crashing when using expo-video-player

**Comment by ihmpavel** [comment] 2020-02-12 09:38
Hi, what version of this package are you using (also @react-native-community/netinfo and expo-av version). (Do you see some errors?)

Can you create some minimal reproduction? (snack.expo.io)

I am unable to simulate this (SDK 36 with latest version is working for me).

**Comment by devramjava** [comment] 2020-02-12 09:42
i'm using "expo-av": "^8.0.0"

**Comment by ihmpavel** [comment] 2020-02-22 11:55
The issue will be closed soon, due to lack of information.

**Comment by ihmpavel** [comment] 2020-03-02 09:11
Closing, can be reopened again.

**Closed by ihmpavel** 2020-03-02 09:11 UTC
Labels: needs more information
